#!/usr/bin/env python3
# -*- encoding: utf-8
if __name__ == "__main__":
    numb = 5
    s = numb
    days = 2
    while days <= 10:
        numb += 2
        s += numb
        days += 1
    print(s)
